version: "3.9"

services:

  postgres:
    container_name: postgres-prb
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DATABASE}
      - PGPORT=${PG_PORT}
      - PGDATA=${PG_DATA}
      - TZ="Europe/Moscow"
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - ./volumes/postgres-prb-data:/var/lib/postgresql/data
      - ./bot/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    container_name: redis-prb
    image: redis:latest
    restart: always
    env_file:
      - .env
    command: --port ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./volumes/redis-prb-data:/bitnami/redis/data

  bot:
    container_name: aiogram-template
    build: .
    restart: on-failure
    env_file:
      - .env
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
  redis-data: