FROM ubuntu:22.04

EXPOSE 8080/tcp

RUN apt install python3 && \
    apt install python3-virtualenv && apt install python3-pip && apt install git

RUN mkdir "/var/coolworld/aiogram_template"

WORKDIR /var/coolworld
RUN git clone https://github.com/coolworld2049/aiogram_template.git /var/coolworld/aiogram_template

WORKDIR /var/coolworld/aiogram_template
RUN pip install -r requirements.txt

ENTRYPOINT ["python", "app.py"]