name: deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 5,17 * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.REMOTE_HOST }}  >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -n ./dist/ root@$85.193.94.190:/var/testbot/aiogram_template
