name: deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *' # Everyday at 12am
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts
        
      - name: Stop service
      - run: sudo systemctl stop $PROJECT_NAME.service;
      
      - name: Deploy with rsync
        run: rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/${{ secrets.SSH_USER }}/{{ github.GITHUB_REPOSITORY }}
      
      - name: Restart service
      - run: sudo systemctl daemon-reload;
      - run: sudo systemctl restart $PROJECT_NAME.service;
      - run: sudo systemctl status $PROJECT_NAME.service;
